<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OneMoreRep</title>
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <?php require __DIR__ . "/partials/_header.phtml"; ?>

    <main>
        <?php require __DIR__ . "/" . $template; ?>
    </main>

    <?php require __DIR__ . "/partials/_footer.phtml"; ?>
</body>
</html>
